[build-system]
requires = [
    "setuptools>=61.0",
    "cython<3",
    "numpy<2",
    "pythran>=0.13.1",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
exclude = ["presentation.py", "examples/*"]

[tool.ruff.lint]
ignore = ["E741"]

